export const mockGroups = [
  {
    id: "1",
    name: "Lagos to Abuja Road Trip",
    destination: "Abuja",
    members: 4,
    maxMembers: 8,
    isPrivate: false,
    trustScore: 78,
    image: "https://picsum.photos/400/200?random=1",
    description: "Looking for travel companions for a Lagos to Abuja road trip this weekend.",
    owner: "Chidi Okeke",
  },
  {
    id: "2",
    name: "Zanzibar Beach Squad",
    destination: "Zanzibar",
    members: 6,
    maxMembers: 10,
    isPrivate: false,
    trustScore: 85,
    image: "https://picsum.photos/400/200?random=2",
    description: "Planning a 7-day Zanzibar trip in July. All welcome.",
    owner: "Amina Yusuf",
  },
  {
    id: "3",
    name: "Accra Culture Trip",
    destination: "Accra",
    members: 3,
    maxMembers: 6,
    isPrivate: true,
    trustScore: 91,
    image: "https://picsum.photos/400/200?random=3",
    description: "Private group for verified travellers heading to Accra in August.",
    owner: "Taiwo Adeyemi",
  },
  {
    id: "4",
    name: "Cape Town Adventure",
    destination: "Cape Town",
    members: 5,
    maxMembers: 8,
    isPrivate: false,
    trustScore: 67,
    image: "https://picsum.photos/400/200?random=4",
    description: "Cape Town trip planned for September. Outdoor activities and city tours.",
    owner: "Ngozi Eze",
  },
];

export const mockMessages = [
  {
    id: "1",
    text: "Hey everyone, really excited about this trip!",
    sender: "Chidi Okeke",
    senderId: "user1",
    timestamp: "10:30 AM",
  },
  {
    id: "2",
    text: "Same here! Has everyone sorted their accommodation?",
    sender: "Amina Yusuf",
    senderId: "user2",
    timestamp: "10:32 AM",
  },
  {
    id: "3",
    text: "I found a great Airbnb for all of us. Sharing the link now.",
    sender: "Taiwo Adeyemi",
    senderId: "user3",
    timestamp: "10:35 AM",
  },
  {
    id: "4",
    text: "Perfect. What time are we leaving on Friday?",
    sender: "Ngozi Eze",
    senderId: "user4",
    timestamp: "10:37 AM",
  },
];

export const mockUser = {
  id: "currentUser",
  name: "Wahab Badmus",
  email: "wahab@travelpal.com",
  trustScore: 82,
  isVerified: true,
  tripsCompleted: 5,
  memberSince: "January 2025",
  bio: "Passionate traveller. Love exploring African cities and cultures.",
};